export const IPC_PYTHON = 'IPC_PYTHON';
export const IPC_INITIAL_REQ = 'IPC_INITIAL_REQ';
export const IPC_INITIAL_RES = 'IPC_INITIAL_RES';
export const IPC_UPDATE_REQ = 'IPC_UPDATE_REQ';
export const IPC_UPDATE_RES = 'IPC_UPDATE_RES';